variables:
  PYTHON: python3
  DEBIAN_FRONTEND: noninteractive
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache/"

cache:
  paths:
    - $CI_PROJECT_PATH/.cache/pip


.common_deps_script: &common_deps_script |
  apk add --no-cache git  # for git+ requirements
  $PYTHON -m pip install setuptools==21 pip==9
  pip install -r test-requirements.txt -r requirements.txt

.common_script: &common_script
  - $PYTHON -m pytest --cov-fail-under=100
  - $PYTHON -m codecov

tests:2.7:
  image: python:2.7-alpine
  variables:
    PYTHON: python2
  before_script:
    - *common_deps_script
  script: *common_script
  coverage: '/Total coverage: \d+\.\d+%/'

tests:3.4:
  image: python:3.4-alpine
  before_script:
    - *common_deps_script
  script: *common_script
  coverage: '/Total coverage: \d+\.\d+%/'

tests:3.5:
  image: python:3.5-alpine
  before_script:
    - *common_deps_script
  script: *common_script
  coverage: '/Total coverage: \d+\.\d+%/'

tests:3.6:
  image: python:3.6-alpine
  before_script:
    - *common_deps_script
  script: *common_script
  coverage: '/Total coverage: \d+\.\d+%/'

tests:3.7:
  image: python:3.7-alpine
  before_script:
    - *common_deps_script
  script: *common_script
  coverage: '/Total coverage: \d+\.\d+%/'

lint:
  image: python:3.5
  before_script:
    - $PYTHON -m pip install setuptools==21 pip==9
    - pip install 'git+https://github.com/coala/coala#egg=coala'
    - pip install 'git+https://github.com/coala/coala-bears#egg=coala-bears'
  script:
    - coala --ci

moban:
  image: python:3.5
  before_script:
    - pip install moban
    - git clone https://github.com/moremoban/pypi-mobans ../pypi-mobans
    - git clone https://github.com/ogrisel/python-appveyor-demo
        ../python-appveyor-demo
    - git clone --depth 1 https://github.com/github/gitignore ../gitignore
    - git clone https://github.com/coala/artwork ../artwork
  script:
    - moban
    - git diff --exit-code
