moban:
  image: python:3.5
  before_script:
    - pip install moban
    - git clone https://github.com/moremoban/pypi-mobans ../pypi-mobans
    - git clone --depth 1 https://github.com/github/gitignore ../gitignore
    # See https://github.com/github/gitignore/pull/2728
    - sed -i 's/ *$//g' ../gitignore/Global/Eclipse.gitignore
  script:
    - moban
    - git diff --exit-code
