name: mobans
contact: coala.analyzer@gmail.com
description: Centralised repo for metadata, templates and assets

configuration:
  template_dir:
    - ../pypi-mobans/
    - ../gitignore/
    - templates/
    - assets/
  configuration: .moban.yaml
targets:
  - .gitignore: coala-gitignore.jj2
copy:
  - templates/requirements.txt.jj2: ../pypi-mobans/templates/requirements.txt.jj2
  - templates/gitignore.jj2: ../pypi-mobans/templates/gitignore.jj2
  - assets/gitignore/Elisp.gitignore: ../gitignore/Elisp.gitignore
  - assets/gitignore/GitBook.gitignore: ../gitignore/GitBook.gitignore
  - assets/gitignore/Jekyll.gitignore: ../gitignore/Jekyll.gitignore
  - assets/gitignore/Java.gitignore: ../gitignore/Java.gitignore
  - assets/gitignore/Maven.gitignore: ../gitignore/Maven.gitignore
  - assets/gitignore/Node.gitignore: ../gitignore/Node.gitignore
  - assets/gitignore/Python.gitignore: ../gitignore/Python.gitignore
  - assets/gitignore/Sass.gitignore: ../gitignore/Sass.gitignore
  - assets/gitignore/Global/VirtualEnv.gitignore: ../gitignore/Global/VirtualEnv.gitignore
  - assets/gitignore/Global/Linux.gitignore: ../gitignore/Global/Linux.gitignore
  - assets/gitignore/Global/Windows.gitignore: ../gitignore/Global/Windows.gitignore
  - assets/gitignore/Global/macOS.gitignore: ../gitignore/Global/macOS.gitignore
  - assets/gitignore/Global/Emacs.gitignore: ../gitignore/Global/Emacs.gitignore
  - assets/gitignore/Global/Vim.gitignore: ../gitignore/Global/Vim.gitignore
  - assets/gitignore/Global/JetBrains.gitignore: ../gitignore/Global/JetBrains.gitignore
  - assets/gitignore/Global/SublimeText.gitignore: ../gitignore/Global/SublimeText.gitignore
  - assets/gitignore/Global/KDevelop4.gitignore: ../gitignore/Global/KDevelop4.gitignore
  - assets/gitignore/Global/Kate.gitignore: ../gitignore/Global/Kate.gitignore
  - assets/gitignore/Global/TextMate.gitignore: ../gitignore/Global/TextMate.gitignore
  - assets/gitignore/Global/VisualStudioCode.gitignore: ../gitignore/Global/VisualStudioCode.gitignore
  - assets/gitignore/Global/Xcode.gitignore: ../gitignore/Global/Xcode.gitignore
  - assets/gitignore/Global/Eclipse.gitignore: ../gitignore/Global/Eclipse.gitignore
  - assets/gitignore/Global/TortoiseGit.gitignore: ../gitignore/Global/TortoiseGit.gitignore
  - assets/gitignore/Global/Tags.gitignore: ../gitignore/Global/Tags.gitignore
