name: mobans
contact: coala.analyzer@gmail.com
description: Centralised repo for metadata, templates and assets

configuration:
  template_dir:
    - ../pypi-mobans/
    - ../python-appveyor-demo/
    - ../gitignore/
    - ../artwork/
    - templates/
    - assets/
  configuration: .moban.yaml
targets:
  - .gitignore: coala-gitignore.jj2
copy:
  - templates/requirements.txt.jj2: templates/requirements.txt.jj2
  - templates/gitignore.jj2: templates/gitignore.jj2
  - templates/setup.py.jj2: templates/setup.py.jj2
  - assets/install.ps1: ../python-appveyor-demo/appveyor/install.ps1
  - assets/gitignore/Elisp.gitignore: Elisp.gitignore
  - assets/gitignore/GitBook.gitignore: GitBook.gitignore
  - assets/gitignore/Jekyll.gitignore: Jekyll.gitignore
  - assets/gitignore/Java.gitignore: Java.gitignore
  - assets/gitignore/Maven.gitignore: Maven.gitignore
  - assets/gitignore/Node.gitignore: Node.gitignore
  - assets/gitignore/Python.gitignore: Python.gitignore
  - assets/gitignore/Sass.gitignore: Sass.gitignore
  - assets/gitignore/Global/VirtualEnv.gitignore: Global/VirtualEnv.gitignore
  - assets/gitignore/Global/Linux.gitignore: Global/Linux.gitignore
  - assets/gitignore/Global/Windows.gitignore: Global/Windows.gitignore
  - assets/gitignore/Global/macOS.gitignore: Global/macOS.gitignore
  - assets/gitignore/Global/Emacs.gitignore: Global/Emacs.gitignore
  - assets/gitignore/Global/Vim.gitignore: Global/Vim.gitignore
  - assets/gitignore/Global/JetBrains.gitignore: Global/JetBrains.gitignore
  - assets/gitignore/Global/SublimeText.gitignore: Global/SublimeText.gitignore
  - assets/gitignore/Global/KDevelop4.gitignore: Global/KDevelop4.gitignore
  - assets/gitignore/Global/Kate.gitignore: Global/Kate.gitignore
  - assets/gitignore/Global/TextMate.gitignore: Global/TextMate.gitignore
  - assets/gitignore/Global/VisualStudioCode.gitignore: Global/VisualStudioCode.gitignore
  - assets/gitignore/Global/Xcode.gitignore: Global/Xcode.gitignore
  - assets/gitignore/Global/Eclipse.gitignore: Global/Eclipse.gitignore
  - assets/gitignore/Global/TortoiseGit.gitignore: Global/TortoiseGit.gitignore
  - assets/gitignore/Global/Tags.gitignore: Global/Tags.gitignore
  - assets/docs/images/coala_logo.svg: artwork/logo/coala_color.svg
  - assets/docs/images/coala-header.png: artwork/logo/coala-header.png
